### ISSUE TITLE
no response while clicking embed button 

### ISSUE THREAD

**Issue by bharath-naik** [samirsayyad/ep_insert_media#1]
hi, i have tried embed button. but while clicking it shows no response .. can you check this out .. thanks

**Comment by samirsayyad** [comment]
Hi
You need to set settings that I have not put in readme yet.
I will update it asap and will tell you.

**Comment by samirsayyad** [comment]
Please have a look 
https://github.com/samirsayyad/ep_insert_media/blob/master/README.md
